# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=64)),
                ('home_number', models.IntegerField()),
                ('flat_number', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.IntegerField(choices=[(1, 'business'), (2, 'private')])),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele_type', models.IntegerField(choices=[(1, 'home'), (2, 'business'), (3, 'private')])),
                ('tele_number', models.IntegerField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbox.Person')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbox.Person'),
        ),
        migrations.AddField(
            model_name='adress',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postbox.Person'),
        ),
    ]
